package com.ohgiraffers.common.support.error;

public enum ErrorCode {

    E500,
    E400,

    // REDIS ERROR
    REDIS_ERROR,
    REDIS_CONN_FAILURE,

    // USER
    USER_NOT_FOUND,
    USER_NOT_FOUND_EMAIL,
    USER_NOT_EQUALS_PASSWORD,
    USER_EXISTS_EMAIL,

    // QUEUE ERROR
    QUEUE_NOT_FOUND,
    QUEUE_EXPIRED,

    // PRODUCT ERROR
    PRODUCT_NOT_FOUND,
    PRODUCT_CATEGORY_NOT_FOUND,
    PRODUCT_UNAUTHORIZED,
    PRODUCT_VALIDATION_ERROR,

    //PROMOTION ERROR
    PROMOTION_SOLDQUANTITY_OVER,
    PROMOTION_NOT_FOUND,
    PROMOTION_STATUS_ERROR

}
