package com.ohgiraffers.common.support.error;

public enum ErrorCode {

    E500,
    E400,

    // REDIS ERROR
    REDIS_ERROR,
    REDIS_CONN_FAILURE,
    REDIS_LOCK_EXPIRED,

    // USER
    USER_NOT_FOUND,
    USER_NOT_FOUND_EMAIL,
    USER_NOT_EQUALS_PASSWORD,
    USER_EXISTS_EMAIL,

    // QUEUE ERROR
    QUEUE_NOT_FOUND,
    QUEUE_EXPIRED,
    QUEUE_NOT_PASSED,
    QUEUE_NOT_COMPLETED,

    // PRODUCT ERROR
    PRODUCT_NOT_FOUND,
    PRODUCT_CATEGORY_NOT_FOUND,
    PRODUCT_UNAUTHORIZED,
    PRODUCT_VALIDATION_ERROR,

    //PROMOTION ERROR
    PROMOTION_SOLDQUANTITY_OVER,
    PROMOTION_NOT_FOUND,
    PROMOTION_STATUS_ERROR,
    PROMOTION_STATUS_INVALID,

    // VALIDATION ERROR
    PROMOTION_ID_INVALID,
    OUT_OF_STOCK,
    QUANTITY_LIMIT_EXCEEDED,

    // USER READER ERROR
    USER_READ_FAILED,
    USER_BALANCE_DECREASE_FAILED,

    // PROMOTION READER ERROR
    PROMOTION_READ_FAILED,
    PROMOTION_STOCK_DECREASE_FAILED,
    // FEIGN ERROR
    FEIGN_CLIENT_ERROR,

    // ORDER DB ERROR
    ORDER_DB_ERROR
}
